version: "3.8"
   
services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  anup_web:
    environment: 
      - COMPOSE_CONVERT_WINDOWS_PATHS=1
    # env_file: .env
    image: anup_web
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - "D:\\Workcult coding\\Docs_django_docker\\code:/code"
    ports:
      - "8000:8000"
    depends_on:
      - db